spring.application.name=e-walled-api
server.port=${SERVER_PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXP}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_TLS}
spring.mail.default-encoding=UTF-8
springdoc.api-docs.enabled=${API_DOCS:true}
springdoc.api-docs.path=${API_DOCS_PATH:/v3/api-docs}
springdoc.swagger-ui.path=${API_DOCS_SWAGGER_PATH:/swagger-ui.html}
spring.jackson.property-naming-strategy=SNAKE_CASE
server.error.whitelabel.enabled=false
logging.level.org.springframework.security=${SECURITY_LOG:DEBUG}
spring.flyway.enabled=${FLYWAY_ENABLE:false}
spring.flyway.locations=${FLYWAY_LOCATION}
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE}
spring.flyway.validate-on-migrate=${FLYWAY_VALIDATE_ON_MIGRATE}
spring.flyway.out-of-order=${OUT_OF_ORDER}
spring.flyway.url=${DB_URL}
spring.flyway.username=${DB_USERNAME}
spring.flyway.password=${DB_PASSWORD}

